### ISSUE TITLE
FireFoam-tutorial flameSpreadWaterSuppressionPanel fails

### ISSUE THREAD

**Issue by linseisen** [OpenFOAM/OpenFOAM-2.3.x#6]
The problem is reproducable by running tutorial flameSpreadWaterSuppressionPanel with the Allrun script. 
The logs for all steps before fireFoam seem to be okay.

Solver version is 2.3.x with hash beginning with e791c532f262, as compiled on January 27th, 2015. Compilation using gcc 4.8.3 20140911 showed no error messages.

PS: It is most unfortunate that adding log-files is not supported by this issue tracker.

**Comment by oilsok** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

oilsok@naver.com 님께 보내신 메일 <[OpenFOAM-2.3.x] FireFoam-tutorial flameSpreadWaterSuppressionPanel fails (#6)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by OpenFOAM** [comment]
Please report bug on Mantis: http://www.openfoam.org/bugs/

**Comment by oilsok** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

oilsok@naver.com 님께 보내신 메일 <Re: [OpenFOAM-2.3.x] FireFoam-tutorial flameSpreadWaterSuppressionPanel fails (#6)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
